# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_fad_score.ipynb.

# %% auto 0
__all__ = ['score', 'main']

# %% ../nbs/03_fad_score.ipynb 5
import argparse
from .sqrtm import sqrtm

# %% ../nbs/03_fad_score.ipynb 6
def score(real_emb_path='real_emb', fake_emb_path='fake_emb'): 
    print(real_emb_path, fake_emb_path)

# %% ../nbs/03_fad_score.ipynb 7
def main(): 
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('real_emb_path', help='Path of files of embeddings of real data', default='real_emb/')
    parser.add_argument('fake_emb_path', help='Path of files of embeddings of fake data', default='fake_emb/')
    args = parser.parse_args()
    score( args.real_emb_path, args.fake_emb_path)
